# advanced remat config structure
# see src/utils/remat_utils.advanced_remat.py for more details

advanced:

 -  name: model
    settings:
        activation_checkpoint_layers:
         - LlamaDecoderLayer
        optimization_barrier_layers:
         - LlamaDecoderLayer
        scan_layers: layers
        offload_tensors:
         - decoder_input # these should not be the same between different components?

 -  name: head
    settings:
        activation_checkpoint_layers:
         - HeadLayer
        optimization_barrier_layers:
         - HeadLayer
        scan_layers: layers
        offload_tensors:
         - head_input
