defaults:
 - llama-fsdp
 - _self_


# Weights

head.input_norm.weight: [fsdp]
head.input_proj.weight: [fsdp, null]
head.embed_samples.weight: [null, fsdp]

head.layers.*.norm.weight: [fsdp]
head.layers.*.mlp.gate_proj.weight: [fsdp, null]
head.layers.*.mlp.up_proj.weight: [fsdp, null]
head.layers.*.mlp.down_proj.weight: [null, fsdp]

head.out_norm.weight: [fsdp]
head.output_proj.weight: [null, fsdp]


# Activations
head.layers.*: [null, [data, fsdp], null, null]
