
# vvvvvvvvvv Don't forget to change this for new experiments vvvvvvvvvv
type: lm_trainer.LMTrainer  # Used to import the trainer from this class

# This config is similar to the hyperparameters of GPT-3 XL which had 1.3B parameters.
# (assuming sequence lengths of 1024)

# total batch size across all devices
global_batch_size: 1024

# run for N steps
max_steps: 1000000

# Save a checkpoint every N steps
checkpoint_interval: 1000


# whether to autocast the forward pass and loss computation.
# currently only supports autocasting to bfloat16
use_autocast: true


multiple_optimizers: 

  main:

    optimizer:
      type: adamw.AdamW
      kwargs:
        lr: 5.0e-5
        betas: [0.9, 0.95]
        eps: 1e-6 
        weight_decay: 0.1

    lr_scheduler:
      type: warmup_stable_decay
      num_warmup_steps: 375
      kwargs:
        num_stable_steps: 1000000
        num_decay_steps: 5000
        min_lr_ratio: 0.0
        warmup_type: linear
        decay_type: linear

  head:

    optimizer:
      type: adamw.AdamW
      kwargs:
        lr: 2.0e-4
        betas: [0.9, 0.95]
        eps: 1e-6 
        weight_decay: 0.1

    lr_scheduler:
      type: warmup_stable_decay
      num_warmup_steps: 375
      kwargs:
        num_stable_steps: 1000000
        num_decay_steps: 5000
        min_lr_ratio: 0.0
        warmup_type: linear
        decay_type: linear


# Defaults to clip the L2 norm of gradients to 1.0.
# Set to null to disable gradient clipping by norm.
max_grad_norm: 1.0
# Defaults to not clip gradients by their absolute value.
# Set to a number to clip gradients by the specified max absolute value.
max_grad_value: null


# You can add any additional configuration options for your trainer here
# They will appear as attributes of config.trainer

num_nuc_samples: 4
nuc_loss_weight: 1.0